spring.application.name=voting-system
# DataSource Configuration
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.driver-class-name=org.postgresql.Driver

# Enable Liquibase
spring.liquibase.enabled=true

# Define the database changelog file (Liquibase migration scripts)
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml


